### ISSUE TITLE
Some minor issues in DotM maps.

### ISSUE THREAD

**Issue by Flecked42** [sezero/quakespasm#7] opened 2021-09-10 03:00 UTC
![spasm0000](https://user-images.githubusercontent.com/90434262/132792055-20b10fd3-a4df-45cf-a695-f70a0e001d0b.png)
![spasm0001](https://user-images.githubusercontent.com/90434262/132792060-5b8b7b0c-3e73-4e30-8e97-e9532337ab2b.png)
Map is mge4m2. 

Saves at the locations.
[saves.zip](https://github.com/sezero/quakespasm/files/7140993/saves.zip)

**Comment by sezero** [comment] 2021-09-10 07:22
Can't see what the issue is (just woke up), does vkquake have the issue?

**Comment by Flecked42** [comment] 2021-09-10 13:51
Yes vkQuake also has the issues.

Sorry the images are a bit dark, but load the saves and you will see.

First image is some weird transparency issue while looking in the water.
Second image some pipes look invisible.

**Comment by vide0hanz** [comment] 2021-09-10 15:48
To me the second screenshot looks like an issue I've been noticing in both vkQuake and QS with certain map geometry and character models are rendering as pitch black. Firing a weapon nearby does illuminate them, however - but otherwise they appear as completely black objects. 

Is this accurate or totally different?

**Comment by sezero** [comment] 2021-09-10 16:26
Sounds like it -- and hasn't it always been that way?

**Comment by vide0hanz** [comment] 2021-09-10 17:10
It's minor and I'm not even sure how to properly debug it, but fwiw I've only noticed this in the rerelease content, and Arcane Dimensions. 

I've got some screenshots I can share later if that's helpful (not at my PC at the moment).

**Comment by sezero** [comment] 2021-09-10 17:29
@ericwa or @Novum would be much more helpful than me in opengl matters.

**Comment by Novum** [comment] 2021-09-10 18:25
There is no  transparency sorting in either QuakeSpasm or vkQuake. I had a branch to fix this, by traversing the BSP back to front, but it's slower and because QS doesn't do it either I put it aside.

As for the black objects: Is this not happening in other source ports?

**Comment by vide0hanz** [comment] 2021-09-10 20:18
@Novum I've observed black geometry and character models in both vkQuake and QSS. Wasn't sure if it was ever worth bringing up though, since I never knew if it was a renderer thing or a lightmap thing, and it happens in both source ports.

I can create a more detailed report regarding some rendering issues on the vkQuake repo if you want. I've noticed some other weird lighting rendering issues, specifically with the mg1 content in the new start hub area.

**Comment by Flecked42** [comment] 2021-09-10 22:39
![spasm0000](https://user-images.githubusercontent.com/90434262/132924737-189f6ef9-6ef4-43ec-8915-a40f3d838fb0.png)
Black monster issue can be found when the monsters are above these grates in mge1m1.

**Comment by vide0hanz** [comment] 2021-09-11 00:20
![vkquake0001](https://user-images.githubusercontent.com/59800033/132929728-d963b477-4709-4a00-b7c1-9c3ea5a6561d.png)

To add to what @Flecked42 posted - this was observed in Arcane Dimensions, both via vkQuake and Quakespasm, also above a grate.

**Comment by Novum** [comment] 2021-09-11 03:46
I've def. seen the black lighting before & always assumed it's just a bug from how the original Quake dynamic model lighting was baked for the map.

**Comment by Flecked42** [comment] 2021-09-11 04:34
> To me the second screenshot looks like an issue I've been noticing in both vkQuake and QS with certain map geometry and character models are rendering as pitch black. Firing a weapon nearby does illuminate them, however - but otherwise they appear as completely black objects.
> 
> Is this accurate or totally different?

The second image is not black geometry, but rather parts of the pipes look invisible.

**Comment by Flecked42** [comment] 2021-09-12 16:46
![spasm0000](https://user-images.githubusercontent.com/90434262/132995868-caae3a95-e514-4a18-874c-1ecb2e55cb44.png)
Further investigating the black monster issue, it seems to happen when the monsters are above clip brushes.

**Comment by sezero** [comment] 2021-10-05 18:09
These issues are fixed in the git repo. Closing.

**Closed by sezero** 2021-10-05 18:09 UTC
