### ISSUE TITLE
Screen flashes are broken on some maps

### ISSUE THREAD

**Issue by Flecked42** [sezero/quakespasm#42] opened 2022-10-10 18:30 UTC
Screen flashes get broken on some maps.

The map in the video is ctsj2_bal from Coppertone Summer Jam 2 pack https://www.quaddicted.com/filebase/ctsj2_1.2.zip
It happens in other maps as well, strange bug.

https://user-images.githubusercontent.com/90434262/194931575-0ce28bfc-5f57-4b6c-9cd2-ae291d3e2e08.mp4

This also happens in QSS, but it doesn't happen in Ironwail or vkQuake.

**Comment by sezero** [comment] 2022-10-10 18:37
I really have no idea about this. @andrei-drexler? (Since the op said it doesn't happen in ironwail..)

**Comment by Flecked42** [comment] 2022-10-10 23:47
Also this issue doesn't happen with 0.94.7

**Comment by sezero** [comment] 2022-10-10 23:52
> Also this issue doesn't happen with 0.94.7

Now that's noteworthy. The lit water patch was the only thing that would affect such a thing??

**Comment by sezero** [comment] 2022-10-11 00:04
CC: @ericwa, @temx

**Comment by ericwa** [comment] 2022-10-11 01:27
I'm not having any luck reproducing this. Here is what my configuration looks like:

- https://www.quaddicted.com/filebase/ctsj2_1.2.zip , loading it by double clicking the .exe then running `game ctsj2` followed by `map ctsj2_bal`
- Windows 11
- https://versaweb.dl.sourceforge.net/project/quakespasm/Windows/quakespasm-0.95.0_win64.zip
- launched `quakespasm.exe` (so, the SDL2 version)
- NVIDIA 517.48 driver
- I tried with a clean config (deleted config.cfg's) so QS started in windowed mode

@Flecked42 can you give details on your system configuration, or see if you spot any differences vs what I tried?

**Comment by ericwa** [comment] 2022-10-11 01:31
> Seems to have something to do with the skybox.
> 
> Type `sky` `""` in the console to remove the skybox and the issue goes away.

There is also this console warning, might be related:

Warning: Sky texture skybal is 128 x 128, expected 256 x 128

**Comment by Flecked42** [comment] 2022-10-11 02:02
@ericwa I have an AMD card, RX 580, using latest drivers 22.10.1

Maybe an AMD only issue?

**Comment by Flecked42** [comment] 2022-10-11 02:12
> 

Ah r_litwater to 0 also makes the issue go away.

**Comment by Flecked42** [comment] 2022-10-11 02:47
Here's a video that shows the issue in more detail

https://streamable.com/so4p9a

**Comment by Flecked42** [comment] 2022-10-11 16:57
Noticed there's an issue in 0.94.7 also. I guess this is the same issue as in 0.95.0 with litwater off.

https://user-images.githubusercontent.com/90434262/195153453-4d028d89-3675-4090-a2ec-77695d96547d.mp4

**Comment by Flecked42** [comment] 2022-10-11 17:13
Guess that's up to you, but i don't think AMD is gonna fix issues in a Quake sourceport.

**Comment by sezero** [comment] 2022-10-11 17:16
@ericwa, @andrei-drexler: Do we have a workaround for this??

**Comment by temx** [comment] 2022-10-13 14:53
Here's a (hopefully zero-cost) workaround: [amd-polyblend-workaround.txt](https://github.com/sezero/quakespasm/files/9777787/amd-polyblend-workaround.txt)

**Comment by sezero** [comment] 2022-10-13 15:56
> Here's a (hopefully zero-cost) workaround: [amd-polyblend-workaround.txt](https://github.com/sezero/quakespasm/files/9777787/amd-polyblend-workaround.txt)

Huh.. Move `glColor4fv` between `glBegin` and `glEnd`, which is actually legal
according to the man page.

Thanks, will apply shortly.

**Comment by sezero** [comment] 2022-10-13 17:32
OK, should be fixed as of https://github.com/sezero/quakespasm/commit/f09b26bb5d5228583ee82dc06e1456f517a95b62, closing.

If you can't build yourself and need win32 or win64 binaries, tell me.

**Closed by sezero** 2022-10-13 17:32 UTC

**Comment by Flecked42** [comment] 2022-10-13 17:54
Not a big deal to me as i use JoeQuake, but if you want me to test it, i would need win64 binaries.

**Comment by sezero** [comment] 2022-10-13 18:14
>  but if you want me to test it, i would need win64 binaries.

Testing would be nice. Here are win64 builds from git master: [qs-w64.zip](https://github.com/sezero/quakespasm/files/9779458/qs-w64.zip)

**Comment by Flecked42** [comment] 2022-10-13 18:34
Looks good, fixed on my end.

**Comment by sezero** [comment] 2022-10-13 18:38
> Looks good, fixed on my end.

Thanks for testing.
